In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv('mock_census.csv', header='infer')

print(df.shape)
df.head()

(28, 6)

,Province Code,City,Population,Gender Ratio,Person's Household,Households
0,115,Town 01,"14,800",0.88,1.7,8706
1,116,Town 02,"17,010",0.92,1.9,8953
2,117,Town 03,"19,220",0.96,2.1,9152
3,118,Town 04,"21,430",1.00,2.3,9317
4,119,Town 05,"22,160",1.04,2.5,8864

In [3]:
#2.1 Total population where Province Code is 117 or 118
df['Population'] = df['Population'].str.replace(',', '').astype(int)
df[df['Province Code'].isin([117, 118])]['Population'].sum()

np.int64(449880)

In [4]:
#2.2 Average population where Gender Ratio is less than 1
df[df['Gender Ratio'] < 1]['Population'].mean().round(0)

np.float64(36515.0)

In [5]:
#2.3 Places where Gender Ratio < 1 and Person's Household < 2.2
df[(df['Gender Ratio'] < 1) & (df["Person's Household"] < 2.2)]

,Province Code,City,Population,Gender Ratio,Person's Household,Households
0,115,Town 01,14800,0.88,1.7,8706
1,116,Town 02,17010,0.92,1.9,8953
2,117,Town 03,19220,0.96,2.1,9152
7,117,Town 08,28790,0.88,2.1,13710
15,115,Town 16,43510,0.92,1.7,25594
16,116,Town 17,44240,0.96,1.9,23284
21,116,Town 22,53810,0.88,1.9,28321
22,117,Town 23,56020,0.92,2.1,26676

In [6]:
#2.4 Sort from most Households to fewest and display first 10
df.sort_values('Households', ascending=False).head(10)

,Province Code,City,Population,Gender Ratio,Person's Household,Households
25,115,Town 26,61170,1.04,1.7,35982
26,116,Town 27,63380,1.08,1.9,33358
27,117,Town 28,65590,1.12,2.1,31233
20,115,Town 21,51600,1.12,1.7,30353
21,116,Town 22,53810,0.88,1.9,28321
22,117,Town 23,56020,0.92,2.1,26676
15,115,Town 16,43510,0.92,1.7,25594
23,118,Town 24,58230,0.96,2.3,25317
24,119,Town 25,58960,1.00,2.5,23584
16,116,Town 17,44240,0.96,1.9,23284